//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.36399
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RecruitPortal.Webparts.QuickLaunchNavigation {
    using System.Web.UI.WebControls.Expressions;
    using System.Web.UI.HtmlControls;
    using System.Collections;
    using System.Text;
    using System.Web.UI;
    using System.Collections.Generic;
    using System.Linq;
    using System.Xml.Linq;
    using Microsoft.SharePoint.WebPartPages;
    using System.Web.SessionState;
    using System.Configuration;
    using Microsoft.SharePoint;
    using System.Web;
    using System.Web.DynamicData;
    using System.Web.Caching;
    using System.Web.Profile;
    using System.ComponentModel.DataAnnotations;
    using System.Web.UI.WebControls;
    using System.Web.Security;
    using System;
    using Microsoft.SharePoint.Utilities;
    using System.Text.RegularExpressions;
    using System.Collections.Specialized;
    using System.Web.UI.WebControls.WebParts;
    using Microsoft.SharePoint.WebControls;
    
    
    public partial class QuickLaunchNavigation {
        
        protected global::System.Web.UI.WebControls.Literal ltrlNavigationHTML;
        
        protected global::System.Web.UI.WebControls.HiddenField hdnIsCurrentUserFullPrivilege;
        
        protected global::System.Web.UI.WebControls.Literal ltrlNavigationDiv;
        
        public static implicit operator global::System.Web.UI.TemplateControl(QuickLaunchNavigation target) 
        {
            return target == null ? null : target.TemplateControl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::System.Web.UI.WebControls.Literal @__BuildControlltrlNavigationHTML() {
            global::System.Web.UI.WebControls.Literal @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.Literal();
            this.ltrlNavigationHTML = @__ctrl;
            @__ctrl.ID = "ltrlNavigationHTML";
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::System.Web.UI.WebControls.HiddenField @__BuildControlhdnIsCurrentUserFullPrivilege() {
            global::System.Web.UI.WebControls.HiddenField @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.HiddenField();
            this.hdnIsCurrentUserFullPrivilege = @__ctrl;
            @__ctrl.ID = "hdnIsCurrentUserFullPrivilege";
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::System.Web.UI.WebControls.Literal @__BuildControlltrlNavigationDiv() {
            global::System.Web.UI.WebControls.Literal @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.Literal();
            this.ltrlNavigationDiv = @__ctrl;
            @__ctrl.ID = "ltrlNavigationDiv";
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void @__BuildControlTree(global::RecruitPortal.Webparts.QuickLaunchNavigation.QuickLaunchNavigation @__ctrl) {
            global::System.Web.UI.WebControls.Literal @__ctrl1;
            @__ctrl1 = this.@__BuildControlltrlNavigationHTML();
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            @__parser.AddParsedSubObject(@__ctrl1);
            global::System.Web.UI.WebControls.HiddenField @__ctrl2;
            @__ctrl2 = this.@__BuildControlhdnIsCurrentUserFullPrivilege();
            @__parser.AddParsedSubObject(@__ctrl2);
            global::System.Web.UI.WebControls.Literal @__ctrl3;
            @__ctrl3 = this.@__BuildControlltrlNavigationDiv();
            @__parser.AddParsedSubObject(@__ctrl3);
            @__ctrl.SetRenderMethodDelegate(new System.Web.UI.RenderMethod(this.@__Render__control1));
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void @__Render__control1(System.Web.UI.HtmlTextWriter @__w, System.Web.UI.Control parameterContainer) {
            parameterContainer.Controls[0].RenderControl(@__w);
            @__w.Write("\r\n");
            parameterContainer.Controls[1].RenderControl(@__w);
            @__w.Write("\r\n\r\n\r\n");
            parameterContainer.Controls[2].RenderControl(@__w);
            @__w.Write("\r\n\r\n\r\n\r\n\r\n<script type=\"text/javascript\">\r\n\r\n    $(document).ready(function () {\r" +
                    "\n\r\n        var IsCurrentUserFullPrivilege = $(\'#");
                                     @__w.Write(hdnIsCurrentUserFullPrivilege.ClientID);

            @__w.Write(@"').val();
        var setArray = [];
        setArray = IsCurrentUserFullPrivilege.split(',');
        var currentUserName = setArray[0];
        var isFullAccess = setArray[1];
        
        if (isFullAccess=='false') {
            $('#ms-designer-ribbon').hide();
        }
        $('.rightmenu li:first-child a').attr('href', '/_layouts/15/signout.aspx');

        $('.rightmenu li:last-child a').html(currentUserName);

    //    /_layouts/15/signout.aspx

    });

</script>");
        }
        
        private void InitializeControl() {
            this.@__BuildControlTree(this);
            this.Load += new global::System.EventHandler(this.Page_Load);
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        protected virtual object Eval(string expression) {
            return global::System.Web.UI.DataBinder.Eval(this.Page.GetDataItem(), expression);
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        protected virtual string Eval(string expression, string format) {
            return global::System.Web.UI.DataBinder.Eval(this.Page.GetDataItem(), expression, format);
        }
    }
}
